### ISSUE TITLE
Feedback docs

### ISSUE THREAD

**Issue by khwerhahn** [tosunthex/CoinGecko_NodeJs#2]
Hi, thanks for the library!

if you're open to feedback then I would suggest improving the docs on how to pass params. It takes some digging to figure this out. Maybe more examples would show how that is done. 

Also, some of the URLs are not up to date.

Thanks!

**Comment by tosunthex** [comment]
Hi @khwerhahn 

Thanks for your feedback but before improving my documentation i need your help. I made a test repository to show usage of the all end points. If you checked that repository, What kind of problems did you encounter ?

And could you send me the list of Urls which are not up to date so i can fix that problem.

**Comment by khwerhahn** [comment]
Not really problems. I would just add an example in the docs on how to pass params into functions. Just makes it faster to grasp. 

```
Params to be passed can be found in the official documentation. 
let data = await coingecko.coins.ohlcById({ id: 'bitcoin', 'vs_currency': 'usd', 'days': '1' });
```
